apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: y836x0owz-go 
  janus-idp.io/tekton: y836x0owz-go
  backstage.io/kubernetes-id: y836x0owz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y836x0owz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml